name: monitoring

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma

    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - uptime-kuma:/app/data

    networks:
      - o2-network

volumes:
  uptime-kuma:

networks:
  o2-network:
    external: true
